### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' in 'C:\Users\algan\OneDrive\Masaüstü\abc\theProject\React\react\node_modules\iyzipay\lib'

### ISSUE THREAD

**Issue by HalilAlgan** [iyzico/iyzipay-node#105]
Module not found: Error: Can't resolve 'fs'  hatasi aliyorum Iyzipay.js`te. Yardimci olabilir misiniz. Tesekkurler.

**Comment by log101** [comment]
@HalilAlgan bu bir backend kütüphanesi, frontendde çalıştıramazsın.

**Comment by thornzz** [comment]
@log101 NextJS server side desteği de bulunuyor. Ancak orada server component içerisinde de kullanmaya çalıştım yine fs ile ilgili bir hata alıyorum. Bir şekilde çalıştırma imkanı bulamaz mıyız?

**Comment by thornzz** [comment]
Nextjs ile iyzico entegrasyonu çalıştırabildim. Yapmanız gereken nextjs serverless functions tarafına istekte bulunup isteği iyzico ile ilgili tüm işlemleri orada handle etmeniz.Böylelikle talepler server tarafta handle edildiği için herhangi bir problem kalmıyor.

**Comment by byasarcse** [comment]
Nodejs Kütüphanesi backend projeleri için kullanılması önerilir. Kütüphaneyi kullanabilmeniz için size özel api&secret key değerleri bulunduğu için, client side projelerde kullanılmaması önerilir.

**Comment by emrecoban** [comment]
@thornzz merhaba, nasıl çalıştırdığınız konusunda biraz daha bilgi verebilir misiniz? veya sample code varsa incelemek isterim. zira api route üzerinde çalıştırmayı denediğimde `Error: ENOENT: no such file or directory, scandir` hatası almaktayım.

Sanıyorum İyzico üyeliğimi 24 saat dolmadan kapattıracağım.
