### ISSUE TITLE
Nextjs "Uncaught TypeError: fs.readdirSync is not a function" hatası.

### ISSUE THREAD

**Issue by Psychep** [iyzico/iyzipay-node#106]
Node.js örneğindeki kodları projemde çalıştırdığımda konsolda  **status: 'success',** mesajını alıyorum ama front kısmında ekte de görebileceğiniz  "Uncaught TypeError: fs.readdirSync is not a function" hatası. beliriyor. 
![image](https://user-images.githubusercontent.com/42694514/199618451-0a7995e8-e647-4c66-b340-55c5f33fb267.png)

![image](https://user-images.githubusercontent.com/42694514/199618507-4ae5f4d9-0c28-43c8-af9e-fc8f669771bd.png)

![image](https://user-images.githubusercontent.com/42694514/199618532-32071242-a77d-4ac2-9c22-a433907d46c5.png)

next.config.js dosyam.
![image](https://user-images.githubusercontent.com/42694514/199618696-4a2a4ed3-d57c-4d17-b393-8eb85eefcd1a.png)

**Comment by EgeOnder** [comment]
Sadece server-side işlemlerinizi yaparken kullanabilirsiniz. Next 13 kullanmıyorsanız `getServerSideProps` içinde kullanmaya dikkat edin. Frontend kısmında çağırdığınız kodu da atarsanız daha kolay yardımcı olurum.

**Comment by Psychep** [comment]
Selamlar, bahsettiğiniz şekilde o problemden kurtuldum fakat farklı bir sorunla karşılaştım. 

![image](https://user-images.githubusercontent.com/42694514/199839328-c05b5029-bccc-42de-a857-0ac9373f2629.png)

kodlarım bu şekilde.
![image](https://user-images.githubusercontent.com/42694514/199839372-b5b4b26f-6e08-479d-a2a6-042b8338596e.png)
şuan aldığım hata ise burada.

**Comment by EgeOnder** [comment]
> 

Next ile alakalı bir sıkıntınız olduğunu düşünmüyorum fakat Iyzipay'i 2 kere importlamışsınız biri ES biri CommonJS importu oradan sıkıntı çıkıyor olabilir.

**Comment by Psychep** [comment]
es importunu kaldırdım hala Izyipaydan türettiğim izyipay değeri tanımlanmamış görünüyor,  
![image](https://user-images.githubusercontent.com/42694514/199952293-5a3b18d5-15c0-4b8d-93d3-3b04c2f5365d.png)

sayfamın en altında  export async function getServerSideProps  ile çalıştırdığımda bir sorun yok ama ben satın al sayfamdaki butonla tetikleyebilmek istiyorum ve bunu bu şekilde yapamadım. 

bana bu konuda yardımcı olabilir misin?  sayfamdaki butona bastığımda alışveriş bilgileri ile birlikte bu fonksiyonu nasıl çalıştırabilirim?

**Comment by piemree** [comment]
Merhabalr. Size önerim nextin api ozelligini kullanmaniz. O şekilde daha sağlıklı olacaktir.

**Comment by Psychep** [comment]
teşekkür ederim, iyzico entegrasyonunu daha sonraya bıraktım. tekrar döndüğümde tavsiyenize uyacağım. Bir sorun yaşayana kadar başlığı kapatıyorum.
