### ISSUE TITLE
Subscription Product Create [errorCode: '100001']

### ISSUE THREAD

**Issue by umerarif01** [iyzico/iyzipay-node#127]
Hi! I am trying to create a subscription product but it gives me this error:
```

null {
  status: 'failure',
  errorCode: '100001',
  errorMessage: 'Sistem hatası',
  systemTime: 1710691331394
}
```

Code:
```
var Iyzipay = require("iyzipay");

const iyzipay = new Iyzipay({
  apiKey: apiKey,
  secretKey: secretKey,
  uri: "https://sandbox-api.iyzipay.com",
});

// Define the data for creating the subscription product
const data = {
  name: "Example Subscription Product",
};

iyzipay.subscriptionProduct.create(data, function (err, result) {
  console.log(err, result);
});
```

Please I need help

**Comment by umerarif01** [comment]
I tested to create a payment and that worked but I can't create subscription product. So I tried to test it with some other API keys which I found online and for some reason with those keys, it worked. Do I need to enable some sort of setting from sandbox dashboard or what?

**Comment by muslumsivri** [comment]
did you find a solution i have the same problem

**Comment by umerarif01** [comment]
You need to contact iyzico api support to enable it. It's disabled by default.

**Comment by muslumsivri** [comment]
thanks @umerarif01  do you have an idea when they will reply my request
