### ISSUE TITLE
Failure request with nodejs - errorCode: 1000 - Geçersiz imza

### ISSUE THREAD

**Issue by rodriguesaalr** [iyzico/iyzipay-node#17]
The request http/https with nodejs using package request return error:

`  Iyzipay API Test
    Checkout Form
null { status: 'failure',
  errorCode: '1000',
  errorMessage: 'Geçersiz imza',
  locale: 'tr',
  systemTime: 1465819429937,
  conversationId: '4aHtyNOoXkPc\/CwZLMKSwQ==' }
`

Note: 
1 - Executed "npm run-script samples"
2 - Method: iyzipay.checkoutFormInitialize
3 - The same request with CURL (shell/PHP) or POSTMAN execute success.

**Comment by sotuzun** [comment]
Did you set your api credentials correct? Especially your secret key?

**Comment by rodriguesaalr** [comment]
Yes, when instantiating the method before in file IyzipaySamples.js

`    before(function (done) {
        iyzipay = new Iyzipay({
            apiKey: 'api_key',
            secretKey: 'secret_key',
            uri: 'https://sandbox-api.iyzipay.com'
        });
        done();
    });`

api_key and secret_key, i substitute the correct values, because i made the same request with curl (shell/php) and executed success.

CURL:

`
curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: IYZWS sandbox-cHIHP8aClBahMcsexnCKILosxo8PXQ3b:lAOSbptT8EIeCnFPRvjc2NhF4y0=" -H "x-iyzi-rnd: 575b10822d370" -H "Cache-Control: no-cache" -H "Postman-Token: 47698cc0-f2d6-d10c-01f9-e1b1e443049b" -d '{"locale":"tr","conversationId":"4aHtyNOoXkPc\/CwZLMKSwQ==","price":"1.01","basketId":"4aHtyNOoXkPc\/CwZLMKSwQ==","paymentGroup":"PRODUCT","buyer":{"id":"4aHtyNOoXkPc\/CwZLMKSwQ==","name":"teste","surname":"da silva \u00e1\u00e9\u00ed\u00f3\u00fa","identityNumber":"11111111111","email":"teste@boacompra.com","gsmNumber":"(4484) 050 955","registrationAddress":"Rua","city":"Maring\u00e1","country":"Turkey","ip":"172.21.112.189"},"billingAddress":{"address":"Rua","contactName":"teste da silva \u00e1\u00e9\u00ed\u00f3\u00fa","city":"Maring\u00e1","country":"Turkey"},"basketItems":[{"id":"1","price":"1.01","name":"produto teste","category1":"BoaCompra","itemType":"VIRTUAL"}],"callbackUrl":"https:\/\/gateway.boacompra.com\/payment.php?callback=&module=iyzi_credit_card&express_action=retrieve&id=4aHtyNOoXkPc\/CwZLMKSwQ==","currency":"TRY","paidPrice":"1.01"}' "https://sandbox-api.iyzipay.com/payment/iyzipos/checkoutform/initialize/ecom"`

**Comment by rodriguesaalr** [comment]
Was sending the JSON string and not a JSON object. The error occurs, because the hash the string is different of object when a Turkish character or accent in some field.

String: da silva \u00e1\u00e9\u00ed\u00f3\u00fa
Object: da silva áéíóú

**Comment by AhmetTanakol** [comment]
Actually, error message is not very explanatory. I'm getting the same error because of string formats.

**Comment by turkishdeveloper** [comment]
Same error here.

**Comment by erata** [comment]
+1 ben de aynı hatayı alıyorum, halbuki önceden çalışıyordu. bu arada java ve iyzipay-sandbox ile çalışıyor sistem şuan. aldığım hata şöyle:
com.iyzipay.model.ThreedsInitialize@2683dd61[
htmlContent=
status=failure
errorCode=1000
errorMessage=Geçersiz imza
errorGroup=
locale=tr
systemTime=1507902397231
conversationId=6156
]

çözümü nedir hatanın, birkaç kişi yazmış  bu sorunla karşılaştıklarına dair ama cevap görünmüyor ortada.
