### ISSUE TITLE
price field is not accepted if the second digit after decimal point is 0 and it gives "Geçersiz İmza" error

### ISSUE THREAD

**Issue by AhmetTanakol** [iyzico/iyzipay-node#19]

**Comment by sotuzun** [comment]
Could you please provide the data you are testing?

**Comment by AhmetTanakol** [comment]
You can try by setting price field as '1.70'

**Comment by sotuzun** [comment]
New version released 1.1.9. Could you please try again? We also have unit tests for this issue.

https://github.com/iyzico/iyzipay-node/blob/develop/test/unit/UtilsTest.js#L71

**Comment by AhmetTanakol** [comment]
It seems fixed now. Thank you
