### ISSUE TITLE
checkoutFormInitialize - Gecersiz imza

### ISSUE THREAD

**Issue by thelaw44** [iyzico/iyzipay-node#31]
https://github.com/iyzico/iyzipay-node/blob/master/samples/IyzipaySamples.js#L232
**Birebir** sample kullanmama rağmen "geçersiz imza" hatası alıyorum. Keylerimin doğruluğuna eminim.

```
var iyzipay = new Iyzipay({
    apiKey: 'sandbox-key',
    secretKey: 'sandbox-key',
    uri: 'https://sandbox-api.iyzipay.com'
});
```

Localhost üzerinde bir Nodejs projesi.

**Comment by sotuzun** [comment]
Bunun gibi entegrasyonla ilgili sorularınızı entegrasyon@iyzico.com adresini yollayınız.
