### ISSUE TITLE
3dshtmlcontent base64 decode

### ISSUE THREAD

**Issue by kurtulussahin** [iyzico/iyzipay-node#34]
Diğer clientlarda 3dshtmlcontent client içinde base64 decode varken, node.js clientında bulunmuyor, ekleyebilir miyiz?

**Comment by sotuzun** [comment]
çok basit şekilde decode ederek html bilgisi alınabilir. Server'dan gelen bilgi client'a direk dönülüyor, bu yüzden araya girmek istemeyiz.
