### ISSUE TITLE
İonic V1 üzerinde iyzipay çalıştırmak?

### ISSUE THREAD

**Issue by mdogan35** [iyzico/iyzipay-node#50]
Merhabalar, iyzipay node js için ionic bir uygulama üzerine nasıl kurarım bu konuda yardımcı olabilir misiniz?
1 aydır ionic V1 ile yaptığım uygulama üzerinde iyzico çalıştırmaya çalışıyorum fakat çalıştıramıyorum, lütfen bu konuda bilgi sahibi birileri yardımcı olabilirse çok ama çok memnun olurum. Site üzerinde Opencart ile gayet sağlıklı çalışıyor ama uygulama da çalıştıramadım.

**Comment by pvtmert** [comment]
merhabalar, oncelikle ionic bir frontend framework'u oldugundan `fs` modulu bulunmuyor, bu sebeple calismiyor

bu kitaplik/modul backend servislerinde kullanilmak uzere tasarlandigi icin muhtemelen baska problemler de cikacaktir. fakat sunucuda calistirarak ve api ile baglanarak kullanabilirsiniz...

sunucu vs ugrasmak istemiyorsaniz, sahsen `firebase` onerebilirim. veya deneyiminiz varsa AWS lambda'da ayni islevi gorecektir. (firebase uzerinde cloud-function kullanarak backend simule etmeniz kolay olacaktir)

tum bunlarin nedenine gelirsek; kisaca secret-key ve api-key'inizi 3. kisilere vermemelisiniz. :)

**Comment by mdogan35** [comment]
Arkadaşım öncelikle verdiğin bilgiler için çok teşekkür ederim. fs modülü bulunmadığı için böyle bir soru sormak zorunda kaldığımı bilmeni isterim, ionic frameworkü hakkında yeni bilgi sahibi olmaya başladım firebase kullanmak daha önce aklıma gelmedi, bunun hakkında araştıracağım ve node js gibi kodların 3. şahıslarla paylaşım yapacağını bilmiyordum bu bilgiler için de ayrıca teşekkür ederim. 
Söylediğin konuları inceleyip bir çalışma yapacağım eğer başarılı olur ise burada paylaşarak bir çok kişiye yardımcı olmayı istiyorum.

**Comment by pvtmert** [comment]
asagida verdigim linkte daha ayrintili bir tartisma mevcut, muhtemelen ionic forumlarinda sorman daha faydali olacaktir.
https://forum.ionicframework.com/t/app-security-store-api-secret-key-for-using-remote-rest-service/17324

direk 3. sahislarla paylasmiyor aslinda, hemen 4. cevapta gorecegin uzere uygulamayi indirip `unzip` yapan herkes secret key vb parolalari hemen gorebilir.

firebase icin su makaleyi takip edebilirsin: https://firebase.google.com/docs/functions/get-started

**Comment by ssdwho** [comment]
Merhaba, acaba google cloud functions ile çalışan bir örnek paylaşabilir misiniz?
