### ISSUE TITLE
Ionic 3  fs.readdirSync is not a function

### ISSUE THREAD

**Issue by RasheedAbdullah** [iyzico/iyzipay-node#51]
I want to integrate the iyzipay service in my Ionic 3 app, when I run the app and initialize the iyzipay object using the following code:

`let iyzipay = new Iyzipay({
		    apiKey: 'sandbox-...',
		    secretKey: 'sandbox-...',
		    uri: 'https://sandbox-api.iyzipay.com'
		});`
I get the following error message:

> ERROR TypeError: fs.readdirSync is not a function
    at Iyzipay._initResources (Iyzipay.js:31)
    at new Iyzipay (Iyzipay.js:25)

please help me to solve this problem,
I guess the problem is that the 'fs' library is for node.js as a server, but ionic apps run in browsers as clients, so what should I do to make the iyzipay-node runs in my Ionic app?

**Comment by pvtmert** [comment]
unfortunately this repository made to usuable as a backend service.

ionic (even though javascript) does not export 'fs' library

you may use firebase or similar backend-as-a-service where your nodejs snippets run in server side without much of a hassle

also similar question asked here: https://stackoverflow.com/questions/46907030/run-time-error-fs-readdirsync-is-not-a-function

**Comment by RasheedAbdullah** [comment]
@pvtmert thanks so much for your response,

I opened the [link above](https://stackoverflow.com/questions/46907030/run-time-error-fs-readdirsync-is-not-a-function) but i could not found any solution there.

> solution:
> you may use firebase or similar backend-as-a-service where your nodejs snippets run in server side without much of a hassle

as I've never tried such a service, do you have any link that guide me how to achieve that?

> edit: also providing api keys and secrets directly to the clients very discouraged
if I should not provide them directly, how should I provide them to the client so that they can call the backend service?

thanks in advance for your time.

**Comment by RasheedAbdullah** [comment]
@pvtmert thanks so much for your response,

I opened the [link above](https://stackoverflow.com/questions/46907030/run-time-error-fs-readdirsync-is-not-a-function) but i could not found any solution there.

> solution:
> you may use firebase or similar backend-as-a-service where your nodejs snippets run in server side without much of a hassle

as I've never tried such a service, do you have any link that guide me how to achieve that?

> edit: also providing api keys and secrets directly to the clients very discouraged
if I should not provide them directly, how should I provide them to the client so that they can call the backend service?

thanks in advance for your time.

**Comment by pvtmert** [comment]
i just posted link because of similary reference of similar use-case :)

solution is creating middleware (cloud, hosting etc) to process requests.

here is a getting started guide for firebase functions, instead of writing to the DB, you can relay requests with proper keys: https://firebase.google.com/docs/functions/get-started

process flow follows:

```

(*) call: sending request

 +--------+ <---[relays the result]----------------+
 | mobile |                                        |
 | device |                                        |
 +--------+ ---[calls middleware]---> +------------+
                                      | your cloud |
                                      | or hosting |
                                      +------------+ <+
                                      |               |
                                [inserts keys]        |
                                      |               |
                            [calls iyzipay backend]   |
                                      |               |
                                      V               |
                            +---------+               |
                            | iyzipay |               |
                            | backend |               |
                            +---------+ ---[transaction result]
```

hope it helps :)

**Comment by RasheedAbdullah** [comment]
Thanks so much. It really helps, although firebase requires billing for any function that calls external urls such as the one needed to call the iyzipay backend.

**Comment by pvtmert** [comment]
create api-key for google maps, you will have 300$ credits in your account monthly...
