### ISSUE TITLE
Methods return errors as result

### ISSUE THREAD

**Issue by saxahan** [iyzico/iyzipay-node#52]
For instance this error object, called method like:

```javascript
iyzipay.threedsPayment.create(payload, function(err, result) {
        console.log(result);
        callback(err || result.errorMessage, result);
    });
````
Why you return errors for in 'result'? Because when I log to the console, if there is an error, the error is always printed via result object not err.

```javascript
{ 
status: 'failure',
 errorCode: '5002',
 errorMessage: 'paymentId is a mandatory parameter',
 locale: 'en',
 systemTime: 1538076694328,
...
}
```

**Comment by pvtmert** [comment]
afaik, error is just proxied from underlying `request` method, which is here for http related errors

this does not mean issue is not valid, imho it should reflect all errors :)

if we going to change methods, we should do it without breaking underlying error object / api compatibility.

**Comment by saxahan** [comment]
Okay maybe then, Promise feature could be added for API compatibility. Anyone who wants to use new feature, then-catch block can be used?

**Comment by pvtmert** [comment]
those would be nice, i notified @yyenigun, maintaining team should take a look and decide what to do.

**Comment by bernaderya1** [comment]
> 
@saxahan 
The paymentId value must be sent in retrievePayment and cancel queries.
