### ISSUE TITLE
Uri cannot be empty

### ISSUE THREAD

**Issue by emrealparslan93** [iyzico/iyzipay-node#53]
```
/node_modules/iyzipay/lib/Iyzipay.js:41
    if (typeof config['uri'] === 'undefined' || config['uri'] === '') throw new TypeError('uri cannot be empty');
                                                                          ^
TypeError: uri cannot be empty
        at Iyzipay._validateIyzipayOptions (/Users/emrealparslan/Projects/x/node_modules/iyzipay/lib/Iyzipay.js:41:77)
```

iyzipay-node: 2.0.28
node: 8.7.0

I get this error while I'm trying to initialize iyzipay module.

All I do is:
`var iyzipay = new Iyzipay({
  apiKey: 'sandbox-xxx',
  secretKey: 'sandbox-xxx',
  uri: 'https://sandbox-api.iyzipay.com'
})`

Should I downgrade the iyzipay-node lib?

**Comment by 07kagan07** [comment]
how did u solve, i have same problem
