### ISSUE TITLE
Subscription Checkout Form retreive problem

### ISSUE THREAD

**Issue by mithundas79** [iyzico/iyzipay-node#69]
I was going through the [Documentation of Iyzico Subscription Api.](https://dev.iyzipay.com/en/subscription/SubscriptionApi.pdf)..

Here in Page 22 after we call the Checkout Form Request Api via [subscriptionCheckoutForm.initialize](https://github.com/iyzico/iyzipay-node/blob/v2.0.35/samples/IyzipaySubscriptionSamples.js#L359)

It says:-

> Once the customer submitted the checkout form, she/he will be redirected to CallBackUrl. At the same time, a post request containing the token will be sent to this URL. You should send another request to check whether the subscription is successfully started or not.

But I do not see any method to perform this operation in the [Subscription Sample Code](https://github.com/iyzico/iyzipay-node/blob/v2.0.35/samples/IyzipaySubscriptionSamples.js)

Can you please help?

**Comment by can3ry** [comment]
Hello sir,

Please see below sample in line 395,

        it('should retrieve  subscription result with checkout form token', function (done) {
            var request = {
                checkoutFormToken: 'c866e6b4-0f2d-4e9c-8adb-abc4f4bfa2ad'
            };

            iyzipay.subscriptionCheckoutForm.retrieve(request, function (err, result) {
                console.log(err, result);
                done();
            });

**Comment by mithundas79** [comment]
@can3ry Thanks for the reply sir... it was really helpful
