### ISSUE TITLE
Subscription status for trial dates

### ISSUE THREAD

**Issue by mithundas79** [iyzico/iyzipay-node#71]
When I have a trial date shall I send the **subscriptionInitialStatus** as Active or Pending, as per Doc it looks like I can send it as Active and if it has a trialPeriod it wont charge immediately... is that true?

**Comment by can3ry** [comment]
Hello Mithun,
Yes. The card won't be charged until the end of trial period.
Please do not hesitate to send your questions to integration@iyzico.com for similar issues.
Thanks

**Comment by mithundas79** [comment]
Thank you @can3ry
