### ISSUE TITLE
Serverless denemeleri

### ISSUE THREAD

**Issue by ssdwho** [iyzico/iyzipay-node#83]
Merhaba, örnek kodu localde denedim "done();" kısmını çıkartınca çalışıyor ancak amacım bunu lambda üzerinde çalıştırmak. Orada bir handler fonksiyon kullanmak gerekiyor ve bunu başaramadım.

`exports.handler = async (event) => {
    await iyzipay.payment.create(request, function (err, result) {
        return err ? err : result;
    });
};`

Sonuç null dönüyor.

**Comment by moahammadalt** [comment]
you are using both callbacks and promises, which Is wrong in theory.

right now promises and async-await are not supported in the client, in order to get your code works, you have to use only callbacks like this:

```
exports.handler = (event) => { 
     iyzipay.payment.create(request, function (err, result) { 
         // do whatever you want with the result here 
     }); 
};
```

**Comment by ssdwho** [comment]
`exports.handler = (event) => { 
     iyzipay.payment.create(request, function (err, result) { 
        return err ? err : result;
     }); 
};`

payment is successful, but the result is still 'null'.

how can I view the response? no document? I could not see. There is only one sample code.

**Comment by moahammadalt** [comment]
you are getting it null because of the wrong implementation of your code.

try to change your code to the one i sent before in the comments and i am sure you will get the desired result.

**Comment by ferasallaou** [comment]
@ssdwho Selam, bu şekilde kullanabilirsin 
```
const makePayment = (request) => {
  return new Promise((Resolve, Reject) => {
    iyzipay.payment.create(request, async function (err, result) {
      if (err) {
        Reject({
          id: 'Payment',
          message: err
        })
      }


      if (result && result.status == 'failure') {
        Reject({
          id: 'Payment Failed',
          message: result.errorMessage
        })
      }

      Resolve(result)
    });
  })
}

const getPayment = await makePayment(requestObject)

```
