### ISSUE TITLE
Angular Kullanımı

### ISSUE THREAD

**Issue by ramazanulucay** [iyzico/iyzipay-node#88]
Merhaba,

Angular için kullanabileceğimiz bir kütüphane var mıdır? 

Saygılarımla.

**Comment by codingwithmanny** [comment]
I don't think they plan on creating an Angular or React library for this because the form is generated from their servers (probably for security reasons). The reason for this is because your API keys need to be kept private (server side) and not shown on the client side (visible in the browser).
