### ISSUE TITLE
React native yardım

### ISSUE THREAD

**Issue by akindizayn1** [iyzico/iyzipay-node#93]
Merhaba,
React native ile geliştirdiğimiz bir mobil uygulamada iyzico kullanmak istiyoruz fakat nasıl yapabileceğimizi bilmiyorum konu hakkında kaynak gösterirmisiniz  yada yardım edebilirmisiniz.

**Comment by ShopskaSalad** [comment]
Selamlar,
Bunun aslında birçok yolu var. Ancak dilerseniz en çok önerdiğimiz CF anlatmak isterim size.
Haydi başlayalım;

### 1. Adım;
İlk olarak https://sandbox-merchant.iyzipay.com/auth/register adresine giderek bir Sandbox hesabı açıyoruz, tüm test operasyonları için burayı kullanmanızı tavsiye ederiz.
Sandbox hesaplarına giriş yapabilmek için gerekli OTP statik olarak 123456’dır.
Ve son olarak, hesabımızı açtığımıza göre artık iyzico API KEY ve SECRET KEY ulaşabiliriz, sol menü Ayarlar > Firma Ayarları.
 
### 2. Adım;
Şimdi sıra CF entegrasyonunuzu kolayca yapabilmekte.
CF temelde 2(iki) sorgudan oluşmakta, bunlar sırasıyla ödeme formu başlatmak ve sonucunu öğrenmek.
Ek olarak, CF için örnek Postman API sorguları https://github.com/ShopskaSalad/iyzipay-postman adresinden bulunabilir, oradan da ayrıntılı olarak inceleyebilirsiniz.
 
**Ödeme Formu Başlatmak**
İlgili linkte anlatıldığı üzere; https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-baslatma
Bu servis adresine; https://sandbox-api.iyzipay.com/payment/iyzipos/checkoutform/initialize/auth/ecom
Gönderilmesi gereken parametrelerle; https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-baslatma#request
Bir HTTP isteğinde bulunmanız gerekmektedir.
 
Eğer alttaki ekran gibi bir cevap alıyorsanız, neredeyse tamamlamış sayılırız;
![image](https://user-images.githubusercontent.com/13609808/102046196-e1cf4c00-3deb-11eb-9f7f-14e0da53cf6b.png)

Dönen cevaptaki paymentPageUrl’den gelen örnek CF ekran görüntüsü;
![image](https://user-images.githubusercontent.com/13609808/102046228-f01d6800-3deb-11eb-84af-b43bab2d8d86.png)

**Ödeme Formu Sonucu**
İlgili linkte anlatıldığı üzere; https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu
Bu servis adresine; https://sandbox-api.iyzipay.com/payment/iyzipos/checkoutform/auth/ecom/detail
Gönderilmesi gereken parametrelerle; https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu#request
Bir HTTP isteğinde bulunmanız gerekmektedir. Sonuçta size detaylı bir cevap gelecektir; https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu#response
 
Eğer cevabı alıyorsanız CF entegrasyonunu tamamlamış bulunmaktasınız!
Burada mdStatus 1 dönen tüm durumlarda ödeme başarılı olmuş demektir.
 
Özetlemek gerekirse, Ödeme Formu Başlatma adımında vereceğiniz callbackUrl adresine gelen response içerisindeki token alınarak, aynı token ile Ödeme Formu Sonucu için istek atmak gerekiyor.
Çeşitli hata senaryolarının önüne geçmek adına, webhook yöntemi de kullanılabilir; https://dev.iyzipay.com/tr/webhooks.

Kolaylıklar!

**Comment by furkancgrtkn** [comment]
Çok teşekkür ederim :)

14 Ara 2020 Pzt 09:09 tarihinde Kamil AKIN <notifications@github.com> şunu
yazdı:

**Comment by ShopskaSalad** [comment]
Rica ederiz. Kolaylıklar 👊  🎉
