### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by ahmetuysal** [iyzico/iyzipay-node#94]
Hi, I noticed some inconsistencies in the documentation (https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-sonucu). For example, in the documentation it clearly says that possible values for CheckoutFormResult Card Family are: `"Bonus", "Axess", "World", "Maximum", "Paraf", "CardFinans", "Advantage"`. However, when I perform a payment with a test card (5892830000000000) given in documentation, checkout form result contains the value `"Bankamatik"` for the card family.

I am really disappointed with developer experience iyzipay provides as I heard many times İyzico is a company who takes pride in its technical team. How can we implement robust integrations when we cannot even trust the official documentation?

Thanks

**Comment by bernaderya1** [comment]
Hi @ahmetuysal, the sandbox environment depends on the mock data, the relevant field has been updated to the maximum.
