### ISSUE TITLE
Hello i need help for install 

### ISSUE THREAD

**Issue by furkancgrtkn** [iyzico/iyzipay-node#95]
Whatever I do, I cannot activate the form or system. Can someone e-mail me who can explain the installation and running?
mail: furkan.cigirtkan@gmail.com
twitter : fufkieps

**Comment by ShopskaSalad** [comment]
Hey Furkan,
Above all, we kindly ask you to check our https://dev.iyzipay.com/tr.
Basically, you need to have a sandbox account to begin.
Then please follow any product as described in the link https://dev.iyzipay.com/tr/odeme-formu/odeme-formu-baslatma.
Let's say you still couldn't manage, drop a message here please.
Happy coding!

**Comment by ShopskaSalad** [comment]
The topic has closed as there are no replies.
