### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by celikdev** [iyzico/iyzipay-node#99]
![Screenshot_12](https://user-images.githubusercontent.com/52114496/123493175-636a2700-d624-11eb-8be6-de96a870131a.png)

İyzipay ve mocha'yı kurdum fakat hala hata alıyorum.

**Comment by byasarcse** [comment]
İlgili test komutu linux ve macOS ta çalışacak şekilde yazılmıştır, test komutunu düzenleyerek testleri çalıştırabilirsiniz.
